### ISSUE TITLE
ERROR: Creating GUI on CentOS using Python Tkinter.

### ISSUE THREAD

**Issue by jeethub26230** [jeethub26230/ERROR-ON-CENTOS-WHILE-CREATING-GUI-Need-Help#1]
# I'm Trying to create a GUI app on CentOS using python Tkinter module but getting following error. There is no proper solution on GOOGLE As well Can anyone help.!

### BElOW IS MY CODE
```
[root@localhost ~]# python3 Python 3.6.8 
(default, Oct  7 2019, 17:58:22)  [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)] on linux  
>>> import tkinter 
>>> from tkinter import * 
>>> box=Tk() 
Traceback (most recent call last):   File "<stdin>", line 1, in <module>   File "/usr/lib64/python3.6/tkinter/__init__.py", line 2023, in __init__     
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync,SPLAY environment variable
```

**Comment by jasvinderchhabra** [comment]
Hi Jeethu,

Did you got the solution for the above problem. I am also looking for the same.
